# Dictionary of variables and formal names for the descriptive excel tables
# If left empty, all the variables will be included, using the column name of the dataframe
# If not empty, only the variables in the dictionary will be used for the descriptive tables,
# they will have the same order as the dictionary, and will use the value provided in the 
# dictionary as the name
#
# Example:
#
# dict_var =	{'Name' : 'Name'
#				 'G': 'Gender'
#				 'H': 'Height'
#				 'W': 'Weight',
#				 'BMI': 'Body Mass Index'}

dict_var = {'EDAD': 'Age, years',
			'Genero': 'Gender, Male',
			'PESO':'Weight, kg',
			'TALLA':'Height, cm',
			'IMC':'Body Mass Index, kg/m^2',
			'HTA':'Hypertension',
			'DL': 'Dyslipidemia',
			'fumador':'Active Smoking',
			'exfumador o fumador':'Smoking History',
			'DM': 'Diabetes',
			'ICC': 'Heart Failure',
			'Previous CVE attempt':'Previous Electric Cardioversion Attempt',			
			'EAC o CI': 'Coronary Artery Disease or Ischemic Cardiomyopathy',
			'ICTUS/AIT PREVIO':'Previous Transient Ischemic Attack or Stroke',
			'ACO previa si no':'History of oral anticoagulation therapy',
			'EAP':'Peripheral Vascular Disease',
			'REUMATICA':'Rheumatic Heart Disease',
			'RESPIRATORIO': 'Pulmonary disease including sleep apnea',
			'NEOPLASIA':'Prior Cancer',
			'SANGRADO PREVIO':'Prior Bleeding',
			'TEP/TVP': 'Venous Thromboembolism',
			'MOVILIDAD':'Impaired Physical Mobility',
			'CF>=2':'NYHA functional class > 1',
			'CF>=3':'NYHA functional class > 2',
			'CF==4':'NYHA functional class > 3',
			'CHADSVASC':'CHA2DS2-VASc score',
			'HATCH':'HATCH score',
			'HASBLED':'HASBLED score',
			'ANEMIA': 'Anemia',
			'Creatinina':'Creatinine, mg/dL',
			'TFG':'Glomerular filtration rate (mL/min/1,73m^2)',
			'FA_paroxistica':'Paroxysmal',
			'FA_persistente1':'Persistent',
			'FA_persistenteLD2':'Long standing persistent',
			'Masa VI': 'LV mass index, g/m^2',
			'FEVI L-M-G':'LVEF < 50%',
			'FEVI M-G':'LVEF < 40%',
			'FEVI G':'LVEF < 30%',
			'HP':'RV systolic pressure, mm Hg',
			'HP low':'At least moderate probability of pulmonary hypertension',
			'HP high':'High probability of pulmonary hypertension',
			'Vol AI': 'LA volume index, mL/m^2',
			'Dil AI LMS':'LA volume index > 35 ml/m2',
			'Dil AI MS':'LA volume index > 42 ml/m2',
			'Dil AI S':'LA volume index > 48 ml/m2',
			'Valvulopatía sign':'Significant valvular heart disease',
			'EM':'Mitral stenosis',
			'IM':'Mitral regurgitation',
			'Eao':'Aortic stenosis',
			'Iao':'Aortic regurgitation',
			'IT':'Tricuspid regurtitation',
			'Prot mec':'Mechanical prosthetic valve',
			'Prot bio':'Biological prosthetic valve',
			'TIEMPO ACO':'Time under anticoagulation, days',
			'AVK O ACOD':'K-Vitamin Antagonist',
			'ACOD':'Direct Oral Anticoagulants',
			'sintrom':'Sintrom (acenocoumarol)',
			'dabigatran':'Dabigatran',
			'rivaroxaban':'Rivaroxaban',
			'apixaban':'Apixaban',
			'edoxaban':'Edoxaban',
			'heparina':'Low-weight-molecular heparin',
			'AA pre': 'Antiarrhythmics before scheduled EC',
			'amiodarona':'Amiodarone before scheduled EC',
			'flecainida':'Flecainide before scheduled EC',
			'dronedarona':'Dronedarone before scheduled EC',
			'AA post':'Antiarrhythmics after scheduled EC',
			'amiodarona post':'Amiodarone after scheduled EC',
			'flecainida post':'Flecainide after scheduled EC',
			'dronedarona post':'Dronedarone after scheduled EC',
			'AINES':'Nonsteroidal anti-inflammatory drugs',
			'AAS':'Aspirin',
			'clopi o tica':'Other Antiaggregants',
			'Doble Antiagregantes':'Dual Antiplatelet Therapy',
			'BB si no':'Beta Blockers',
			'IECAS/ARA II':'ACE inhibitors / Angiotensin II receptor blocker',
			'SAC VAL':'Sacubitril/Valsartan',
			'CC s n':'Calcium Antagonists',
			'ARM':'Aldosterone receptor antagonist',			
			'DIGOXINA':'Digoxin',
			'CHOQUES':'Number of Shocks',
			'ENERGIA MAX':'Max Energy, J',
			'ICC 2m':'Heart Failure at 2 month follow up',
			'ICTUS 2m':'Stroke at 2 month follow up',
			'AIT 2m':'Transient Ischemic Attack at 2 month follow up',
			'ES 2m':'Embolism 2m',
			'IAM 2m':'Acute Myocardial Infarction at 2 month follow up',
			'MUERTE CV 2m':'Cardiovascular Death 2m',
			'MUERTE CC 2m':'Any Cause Death 2m',
			'SANG MAYOR 2m':'Major Bleeding 2m',
			'SANG FATAL 2m':'Fatal Bleeding 2m',
			'SANG GI 2m':'Gastrointestinal Bleeding 2m',
			'SANG IC 2m':'Intracraneal Bleeding 2m',
			'CUALQ SANG 2m':'Any Bleeding 2m',
			'ICC 2m':'Heart Failure 2m',
			'Trombo 2m':'Thrombus 2m',
			'BAV/Bradi-taqui 2m':'Tachycardia-bradycardia syndrome / AV block 2m',
			'ICTUS':'Stroke before 6 month follow up',
			'AIT':'Transient Ischemic Attack before 6 month follow up',
			'ES':'Embolism 6m',
			'IAM':'Acute Myocardial Infarction before 6 month follow up',
			'MUERTE CV':'Cardiovascular Death',
			'MUERTE CC':'Any cause Death',
			'SANG MAYOR':'Major Bleeding 6m',
			'SANG FATAL':'Fatal Bleeding 6m',
			'SANG GI':'Gastrointestinal Bleeding 6m',
			'SANG IC':'Intracraneal Bleeding before 6 month follow up',
			'CUALQ SANG':'Any Bleeding 6m',
			'ICC.1':'Heart Failure before tm',
			'Trombo en algun estudio':'Thrombus 6m',
			'BAV/Bradi-taqui':'Tachycardia-bradycardia syndrome / AV block 6m',
			'CV EXITOSA':'Long term successful CV',
			'CV ESPONTÁNEA': 'Spontaneous restoration of SR',
			'CV FARMA': 'Pharmacologic CV',
			'CV EFECTIVA': 'Any CV',
			'RECAIDA': 'Recurrence of AF after CV'
			}
